### ISSUE TITLE
Business Owners Request Form

### ISSUE THREAD

**Issue by sbathgate** [yyjlocalsforlocals/yyjlocalsforlocals#3]
We have fired together a quick google form for business requests found here: [Business Request Form](https://docs.google.com/forms/d/1lpPisOBvfMXAK-SOmukinIB2oEAFvWMVaUbbhyBPvuc/viewform?edit_requested=true)

If anyone has ideas for improvement, DM Eve O on the slack channel!

**Comment by hannan-emily** [comment]
This is done now - Nathan added it to the website after Eve built the form
